config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    collection do
      get 'top'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    validates :name, presence: true
    has_many :review, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

    before_action :current_restaurant, only: [:show, :edit, :update, :destroy]

    def index
        @restaurants = Restaurant.all
    end

    def show
        @reviews = Review.where(restaurant: params[:id])
    end

    def new
        @restaurant = Restaurant.new
    end
    
    def create
        @restaurant = Restaurant.create(restaurant_params)
    
        redirect_to restaurants_path
    end

    def edit
    
    end
    
    def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
    end
    
    def destroy
        @restaurant.destroy
        redirect_to restaurants_path
    end

    def top
        @restaurants = Restaurant.where(rating: 5)
      end

    private
    def restaurant_params
        params.require(:restaurant).permit(:name, :rating)
    end

    def current_restaurant
        @restaurant = Restaurant.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :current_restaurant, only: [:new, :create, :edit, :update, :destroy]
    before_action :current_review, only: [:edit, :update, :destroy]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.restaurant = @restaurant
        @review.save
        redirect_to restaurant_path(@restaurant)
    end

    def edit
    
    end
    
    def update
        @review.update(review_params)
        redirect_to restaurant_path(@restaurant)
    end

    def destroy
        @review.destroy
        redirect_to restaurant_path(@restaurant)
    end

    private

    def review_params
        params.require(:review).permit(:content, :rating)
    end

    def current_review
        @review = Review.find(params[:id])
    end

    def current_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :rating, placeholder: "rating" %>

  <%= form.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h3>Update a restaurant</h3>

<%= render "form", restaurant: @restaurant  %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
      <td><%= button_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant), method: 'get'%></td>
      <td><%= button_to "Remove", restaurant_path(restaurant), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
   
</table>
<br>
<%= button_to 'Add a New Restaurant', new_restaurant_path, method: 'get'%>
<br>
<%= button_to 'Top Restaurants', top_restaurants_path, method: 'get' %>

app/views/restaurants/new.html.erb
<h3>Create a restaurant</h3>

<%= render "form", restaurant: @restaurant  %>

app/views/restaurants/show.html.erb
<h1>Restaurant</h1>

<div>
nom : <%= @restaurant.name %>
<br>
rate : <%= @restaurant.rating %>
</div>
<br>

<% if @restaurant.review.count != 0 %>
<hr>
    <div>
        <p>Review</p>

            <ul>
                <% @restaurant.review.each do |r| %>
                <li>
                                content : <%= r.content %>
                                <br>
                                rate : <%= r.rating %>
                                <br>
                                <%= button_to "Edit", edit_restaurant_review_path(@restaurant, r), method: 'get'%>
                                <%= button_to "Remove", restaurant_review_path(@restaurant, r), method: 'delete', data: { confirm: 'Are you sure?' } %>
                            </li>
                <% end %>
        </ul>

    </div>
<% end %>


<br>
<%= button_to 'Add review', new_restaurant_review_path(@restaurant), method: 'get' %>
<br>
<%= button_to 'HomePage', restaurants_path(), method: 'get'%>

app/views/restaurants/top.html.erb
<h1>Top Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
  <% end %>
</ul>

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review] do |f| %>
  <%= f.text_field :content, placeholder: "content"%>
  <%= f.text_field :rating,  placeholder: "rating" %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= render "form", restaurant: @restaurant, review: @review %>

app/views/reviews/new.html.erb
<h1>Create Review</h1>
<%= render "form", restaurant: @restaurant, review: @review %>